ansible_become_password: "{{ vault_ansible_become_password }}"
firewalld_default_zone: "drop"
#firewalld_interfaces:
#  - { interface: "docker0", zone: "trusted", state: "enabled" }
#  - { interface: "wg0", zone: "trusted", state: "enabled" }
#  - { interface: "eth1", zone: "public", state: "disabled" }
#firewalld_sources:
#  - { source: "10.0.0.0/8", zone: "external", state: "enabled" }
#  - { source: "192.168.1.0/24", zone: "trusted", state: "disabled" }
#firewalld_masquerade:
#  - { zone: "external", state: "enabled" }


some_var: "{{ vault_some_var }}"
some_key: "{{ vault_some_key }}"